### ISSUE TITLE
[1.14.4] Players unable to log in with The Midnight on the server and client- see logs.

### ISSUE THREAD

**Issue by ProsperCraft** [Cryptic-Mushroom/The-Midnight#274]
**Client Logs-**
Log files were scrolling a million miles a second.

[Client.zip](https://github.com/Cryptic-Mushroom/The-Midnight/files/3499651/Client.zip)

Client Stacktrace exceprt-
https://gist.github.com/ProsperCraft/99b0f98a13d177eb314fbda05782ba27

**Server Files-**

[Server.zip](https://github.com/Cryptic-Mushroom/The-Midnight/files/3499653/Server.zip)

**Comment by gegy1000** [comment]
Odd, I've been able to join servers with just Midnight installed so I wonder if this is a compatibility issue

**Comment by hamsterpowerftw** [comment]
> Odd, I've been able to join servers with just Midnight installed so I wonder if this is a compatibility issue

Having the same issue server works fine. According to the logs it's a client issue.

**Comment by MrKashew** [comment]
Same, unable to login to 1.14.4 server, however singleplayer crashes are now fixed with latest version.

**Comment by ProsperCraft** [comment]
Tested again with forge .46, Still not able to log in

![9eb390fec69c0df0d377d4a3d98bb672](https://user-images.githubusercontent.com/4427684/63118198-9e946d00-bf5a-11e9-9a2d-85eb480a8e52.png)

[can'tlogin.zip](https://github.com/Cryptic-Mushroom/The-Midnight/files/3506796/can.tlogin.zip)

**Comment by SmellyModder** [comment]
That looks like more things than just midnight
Did you try running it standalone?

**Comment by ProsperCraft** [comment]
No, not interested in running a midnight only server, the other 150 mods get along ok :)

**Comment by SmellyModder** [comment]
I'm just wondering because it could be another mod having an incompatibility with Midnight

**Comment by Khytwel** [comment]
It's from the forge, Gegy can't fix it

**Comment by gegy1000** [comment]
There isn't anything we can do about it, it's to do with how dimensions are registered in Forge. The place where dimensions get registered is only called on the server (including integrated server)

**Comment by gegy1000** [comment]
Basically for now I've just changed the mod to log a warning instead of hard crashing in a broken state like this. Can give this a go https://ci.gegy1000.net/job/Midnight/809/

**Comment by ProsperCraft** [comment]
Mine and Slash has included dimensions and YAMDA has included dimensions since the start of 1.14 and they work great, perhaps take a peek how they do it?

**Comment by gegy1000** [comment]
They're able to avoid needing the dimension type before Forge syncs it over the registry I imagine

**Comment by ProsperCraft** [comment]
That build worked! pushed to curse :)
